import { Noto_Sans_JP } from "next/font/google";
import type { Metadata } from "next";
import "@/styles/globals.css";
import { HeaderDashboard } from "@/components/Header/Dashboard";
import { Header } from "@/components/Header";

const font = Noto_Sans_JP({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
